### ISSUE TITLE
Format step name If the program content comes from stdin

### ISSUE THREAD

**Issue by Yancey0623** [sql-machine-learning/fluid#23]
reproduce bash command:

``` bash
echo 'import fluid
> @fluid.task
> def hello():
>     fluid.step(image="ubuntu", cmd=["echo"], args=["hello"])
> hello()
> ' | python -u
```

the generated YAML:
``` yaml
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: hello
spec:
  inputs:
    params: []
    resources: []
  outputs:
    resources: []
  steps:
  - args:
    - hello
    command:
    - echo
    image: ubuntu
    name: <stdin>-4
---
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: hello-run
spec:
  inputs:
    params: []
    resources: []
  outputs:
    resources: []
  taskRef:
    name: hello
```

where the step name is invalid: 
``` text
Task step name must be a valid DNS Label, For more info refer to https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
```
